name: Elecrow ESP32P4 interface TEST
version: "1.0.4"
slug: crow_ws_panel_test
description: Test version of Home Assistant Browser for Elecrow ESP32P4 Advance panel
url: https://github.com/Filimonova-Ekaterina/crow-ha-dop
arch:
  - amd64
  - aarch64
init: false
apparmor: false
ports:
  "3000/tcp": 3000
ports_description:
  "3000/tcp": WebSocket stream + touch input for the panel device

